[package]
name = "refineid-android-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "=0.22.4"
refineid-apdu = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-auth = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-atr = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-digest = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-pkcs15 = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-sign = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }
refineid-x509 = { git = "https://github.com/ReFineID/refineid-core.git", rev = "d264da6c55d8cbd6fdf4cc41179731ecc1a20e1e" }

[lints.rust]
missing_docs = "warn"
unsafe_code = "warn"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
